use_frameworks!

platform :ios, '10.0'

target 'FFUITool_Example' do
  pod 'FFUITool', :path => '../'

  target 'FFUITool_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
